### ISSUE TITLE
Add Image Capture intent intercept

### ISSUE THREAD

**Issue by mubashir-rehman** [k3b/intent-intercept#14] opened 2021-08-08 19:51 UTC
Further details are here https://github.com/MuntashirAkon/AppManager/issues/549

**Comment by k3b** [comment] 2021-08-08 20:17
todo:

add these to androidmanifest.xml

    android.media.action.VIDEO_CAPTURE
    android.media.action.IMAGE_CAPTURE
    android.media.action.IMAGE_CAPTURE_SECURE

according to https://commonsware.com/blog/2020/08/16/action-image-capture-android-r.html this will not work any more on android-11 and later

**Comment by k3b** [comment] 2021-08-08 20:51
available in v4.0.1

**Comment by mubashir-rehman** [comment] 2021-08-09 08:50
Can you please add IzzyOnDroid(https://apt.izzysoft.de/fdroid/) repo along with fdroid because fdroid takes some time ot publish the new release?

**Comment by mubashir-rehman** [comment] 2021-08-09 09:44
@IzzySoft Can you pleaase add this repo?

**Comment by MuntashirAkon** [comment] 2021-08-10 03:20
_Bad idea._ Publishing the same app in two different repositories would make F-Droid's official client confused, which happened  in my case: F-Droid's still displaying that the last update to App Manager was 4 months ago. The solution could be to publish it under another name.

**Comment by IzzySoft** [comment] 2021-08-11 08:39
@MuntashirAkon that depends on where the user has installed the app from (at least that's the theory) and whether "show incompatible" is turned on (according to some sources, also on the order the indexes are pulled/merged). Ask the FairEmail users who pushed MB to have the app in my repo as well. It's there with the very same package name as in F-Droid (as are several other apps) and I didn't see any complaints yet. Same for Catima, which I have installed via my repo and receive updates allright (2..5 days before they show up in F-Droid).

Last word has the author of the app :smile:

**Comment by MuntashirAkon** [comment] 2021-08-11 08:54
So, why does F-Droid client show changelog from v2.5.24 when the latest version is v2.6.2 and continue to suggest that one? I've got so many complaints regarding latest update not being showed up that I had to post specific instructions for F-Droid users on my Telegram channel.

| Shot 1 | Shot 2 
| ---- | ---- 
| ![Screenshot_20210811-144155_F-Droid](https://user-images.githubusercontent.com/8176128/128999022-4c656c50-2574-43b8-b40a-eb81f9edf259.png) | ![Screenshot_20210811-144204_F-Droid](https://user-images.githubusercontent.com/8176128/128999043-82ea12fb-4159-43e9-a1c3-3e0cd96ab76d.png)

**Comment by k3b** [comment] 2021-08-11 10:58
the last question has nothing to do with intent-intercept so i close this ticket.

to answer question of @mubashir-rehman : 

the f-droid app shows me

* 2.6.2 from f-droid
* 2.6.1 from f-droid
* 2.6.0 from f-droid
* 2.5.24 PRE from izzy
* 2.5.23 PRE from izzy
* 2.5.22 PRE from izzy

you cannot update the f-droid-version from the izzy-version (and vise versa)
so users who installed from izzy have to uninstall first to get most recent version from f-droid.

**Closed as completed by k3b** 2021-08-11 10:58 UTC
Labels: enhancement

**Comment by IzzySoft** [comment] 2021-08-11 12:11
> So, why does F-Droid client show changelog from v2.5.24 when the latest version is v2.6.2

Because the first one is the suggested version – and that's what the changelog is shown for. I could tell you more if you'd have opened the details for the two, but my guess by the above is you've installed from my repo (details as in the post from @k3b exactly before this one). So fixing is easy: Release a newer PRE :laughing:

**Comment by MuntashirAkon** [comment] 2021-08-11 12:29
> I could tell you more if you'd have opened the details for the two, but my guess by the above is you've installed from my repo

As you can see in the screenshot above: I haven't installed any of the variants. Even if I install the F-Droid version, I would get the same thing, and it gets worse: It doesn't even report an update. I think you will understand the situation better if you try it yourself (and maybe report it too since it's very easy to reproduce). I'm really serious on this one as some F-Droid users thought that the project was abandoned since there was no update for months 😞 (even though there was). Other clients such as Aurora Droid do not have this issue (well, they have many other issues but not this one).

> So fixing is easy: Release a newer PRE 😆

The master branch is currently too unstable for a pre-release. As a result, only the stable variants were pushed in the last four months or so.

---

Anyway, I'll stop here since it's going too off-topic.

**Comment by IzzySoft** [comment] 2021-08-11 20:38
> I haven't installed any of the variants.

Ah – I've indeed missed that, apologies! I knew something irritated me but I couldn't pinpoint what it was: no "installed" label at all…

If other clients (like Aurora or F-Droid Classic) don't have that issue, it's clearly a client issue and should be handled there. Sorry, but I neither have the time to fiddle with it, nor am I into the client development (I'm no Android dev at all).

> The master branch is currently too unstable for a pre-release. As a result, only the stable variants were pushed in the last four months or so.

Ah, I see – was already wondering. And yes, we're drifting out :see_no_evil:
